// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientRootLayout from "./ClientRootLayout"; // Import the Client-side layout

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientRootLayout>
          {children}
        </ClientRootLayout>
      </body>
    </html>
  );
}
